TRUNCATE TABLE CHIPS_STG.PS_ACTION_TBL;

INSERT INTO CHIPS_STG.PS_ACTION_TBL(
   ACTION,
   EFFDT,
   EFF_STATUS,
   ACTION_DESCR,
   ACTION_DESCRSHORT,
   OBJECTOWNERID,
   LASTUPDDTTM,
   LASTUPDOPRID,
   SYSTEM_DATA_FLG
)
SELECT
   ACTION,
   EFFDT,
   EFF_STATUS,
   ACTION_DESCR,
   ACTION_DESCRSHORT,
   OBJECTOWNERID,
   LASTUPDDTTM,
   LASTUPDOPRID,
   SYSTEM_DATA_FLG
FROM   MHRGRP.PS_ACTION_TBL@CHIPS_LINK;

COMMIT;