TRUNCATE TABLE CHIPS_STG.PS_ACTN_REASON_TBL;

INSERT INTO CHIPS_STG.PS_ACTN_REASON_TBL(
  ACTION,
  ACTION_REASON,
  EFFDT,
  EFF_STATUS,
  DESCR,
  DESCRSHORT,
  OBJECTOWNERID,
  SYSTEM_DATA_FLG,
  LASTUPDDTTM,
  LASTUPDOPRID
)
SELECT
  ACTION,
  ACTION_REASON,
  EFFDT,
  EFF_STATUS,
  DESCR,
  DESCRSHORT,
  OBJECTOWNERID,
  SYSTEM_DATA_FLG,
  LASTUPDDTTM,
  LASTUPDOPRID
FROM  MHRGRP.PS_ACTN_REASON_TBL@CHIPS_LINK;

COMMIT;