TRUNCATE TABLE CHIPS_STG.PS_BUS_UNIT_TBL_HR;

INSERT    INTO CHIPS_STG.PS_BUS_UNIT_TBL_HR (
   BUSINESS_UNIT,
   ACTIVE_INACTIVE,
   DESCR,
   DESCRSHORT,
   BUSINESS_UNIT_DUP,
   DEFAULT_SETID,
   BUSINESS_UNIT_AM,
   BUSINESS_UNIT_AP,
   BUSINESS_UNIT_AR,
   BUSINESS_UNIT_BAL,
   BUSINESS_UNIT_BD,
   BUSINESS_UNIT_BI,
   BUSINESS_UNIT_GL,
   BUSINESS_UNIT_IN,
   BUSINESS_UNIT_OM,
   BUSINESS_UNIT_PC,
   BUSINESS_UNIT_PO
)
SELECT
   BUSINESS_UNIT,
   ACTIVE_INACTIVE,
   DESCR,
   DESCRSHORT,
   BUSINESS_UNIT_DUP,
   DEFAULT_SETID,
   BUSINESS_UNIT_AM,
   BUSINESS_UNIT_AP,
   BUSINESS_UNIT_AR,
   BUSINESS_UNIT_BAL,
   BUSINESS_UNIT_BD,
   BUSINESS_UNIT_BI,
   BUSINESS_UNIT_GL,
   BUSINESS_UNIT_IN,
   BUSINESS_UNIT_OM,
   BUSINESS_UNIT_PC,
   BUSINESS_UNIT_PO
FROM  MHRGRP.PS_BUS_UNIT_TBL_HR@CHIPS_LINK;

COMMIT;
