TRUNCATE TABLE CHIPS_STG.PS_CAN_NOC_TBL;

INSERT    INTO CHIPS_STG.PS_CAN_NOC_TBL (
  CAN_NOC_CD,
  EFFDT,
  DESCR,
  CAN_NOC_OCC_GROUP,
  SKILL_LEVEL,
  SKILL_TYPE
)
SELECT
  CAN_NOC_CD,
  EFFDT,
  DESCR,
  CAN_NOC_OCC_GROUP,
  SKILL_LEVEL,
  SKILL_TYPE
FROM  MHRGRP.PS_CAN_NOC_TBL@CHIPS_LINK;

COMMIT;
