TRUNCATE TABLE CHIPS_STG.PS_DEDUCTION_TBL;

INSERT    INTO CHIPS_STG.PS_DEDUCTION_TBL (
   PLAN_TYPE,
   DEDCD,
   EFFDT,
   DESCR,
   DESCRSHORT,
   DED_PRIORITY,
   SPCL_PROCESS,
   MAX_PAYBACK,
   MAX_ARREARS_PAYBK,
   MAX_ARREARS_FACTOR,
   GVT_DIST_DEST,
   GVT_REPORTING_CD,
   GVT_TIME_SENSITIVE,
   PERMANENCY_NLD,
   TAX_CLASS_NLD,
   UNION_CD
)
SELECT
   PLAN_TYPE,
   DEDCD,
   EFFDT,
   DESCR,
   DESCRSHORT,
   DED_PRIORITY,
   SPCL_PROCESS,
   MAX_PAYBACK,
   MAX_ARREARS_PAYBK,
   MAX_ARREARS_FACTOR,
   GVT_DIST_DEST,
   GVT_REPORTING_CD,
   GVT_TIME_SENSITIVE,
   PERMANENCY_NLD,
   TAX_CLASS_NLD,
   UNION_CD
FROM  MHRGRP.PS_DEDUCTION_TBL@CHIPS_LINK;

COMMIT;



