TRUNCATE TABLE CHIPS_STG.PS_EMPL_CTG_L1;

INSERT    INTO CHIPS_STG.PS_EMPL_CTG_L1 (
  SETID,
  LABOR_AGREEMENT,
  EMPL_CTG,
  EFFDT,
  EFF_STATUS,
  DESCR,
  DESCRSHORT,
  SEQUENCE_NBR,
  CATEGORY_2483_FRA,
  BILAN_STAT_CD_FRA,
  NBR_COLUMNS_FRA,
  DESCR1_FRA,
  DESCR2_FRA,
  DESCR3_FRA,
  DESCR4_FRA,
  DESCR5_FRA,
  CATEGORY_FORCEM,
  SOC_SEC_WRK_GRP_CD,
  SCHEME_ID_ESP,
  AGREEMENT_END_DT,
  COMMENTS
)
SELECT
  SETID,
  LABOR_AGREEMENT,
  EMPL_CTG,
  EFFDT,
  EFF_STATUS,
  DESCR,
  DESCRSHORT,
  SEQUENCE_NBR,
  CATEGORY_2483_FRA,
  BILAN_STAT_CD_FRA,
  NBR_COLUMNS_FRA,
  DESCR1_FRA,
  DESCR2_FRA,
  DESCR3_FRA,
  DESCR4_FRA,
  DESCR5_FRA,
  CATEGORY_FORCEM,
  SOC_SEC_WRK_GRP_CD,
  SCHEME_ID_ESP,
  AGREEMENT_END_DT,
  COMMENTS
FROM  MHRGRP.PS_EMPL_CTG_L1@CHIPS_LINK;

COMMIT;




