TRUNCATE TABLE CHIPS_STG.PS_SETID_TBL;

INSERT    INTO CHIPS_STG.PS_SETID_TBL (
  SETID,
  DESCR,
  DESCRSHORT,
  PARTIAL_SHARING,
  DESCRLONG
)
SELECT
  SETID,
  DESCR,
  DESCRSHORT,
  PARTIAL_SHARING,
  DESCRLONG
FROM  MHRGRP.PS_SETID_TBL@CHIPS_LINK;

COMMIT;