TRUNCATE TABLE CHIPS_STG.PS_SAL_STEP_TBL;

INSERT    INTO CHIPS_STG.PS_SAL_STEP_TBL (
   SETID,
   SAL_ADMIN_PLAN,
   GRADE,
   EFFDT,
   STEP,
   CURRENCY_CD,
   HOURLY_RT,
   MONTHLY_RT,
   ANNUAL_RT,
   INCREM_MONTHS,
   INCREM_HOURS,
   DAILY_RT,
   GVT_BIWEEKLY_RT,
   GVT_INCREM_DAYS,
   GVT_INCREM_WEEKS,
   GVT_STEP,
   GVT_WGI_ADJ,
   CLASSN_CURRENT_AUS,
   APS_MIN_CLS_AUS,
   APS_MAX_CLS_AUS,
   STEP_DESCR
)
SELECT
   SETID,
   SAL_ADMIN_PLAN,
   GRADE,
   EFFDT,
   STEP,
   CURRENCY_CD,
   HOURLY_RT,
   MONTHLY_RT,
   ANNUAL_RT,
   INCREM_MONTHS,
   INCREM_HOURS,
   DAILY_RT,
   GVT_BIWEEKLY_RT,
   GVT_INCREM_DAYS,
   GVT_INCREM_WEEKS,
   GVT_STEP,
   GVT_WGI_ADJ,
   CLASSN_CURRENT_AUS,
   APS_MIN_CLS_AUS,
   APS_MAX_CLS_AUS,
   STEP_DESCR
FROM  MHRGRP.PS_SAL_STEP_TBL@CHIPS_LINK;

COMMIT;