TRUNCATE TABLE CHIPS_STG.PS_SET_CNTRL_REC;

INSERT    INTO CHIPS_STG.PS_SET_CNTRL_REC (
  SETCNTRLVALUE,
  REC_GROUP_ID,
  RECNAME,
  SETID
)
SELECT
  SETCNTRLVALUE,
  REC_GROUP_ID,
  RECNAME,
  SETID
FROM  MHRGRP.PS_SET_CNTRL_REC@CHIPS_LINK;

COMMIT;