TRUNCATE TABLE CHIPS_STG.PS_TGB_CNOCSUB_TBL;

INSERT    INTO CHIPS_STG.PS_TGB_CNOCSUB_TBL (
   CAN_NOC_CD,
   EFFDT,
   TGB_CAN_NOC_SUB_CD,
   DESCR,
   DESCRSHORT
)
SELECT
   CAN_NOC_CD,
   EFFDT,
   TGB_CAN_NOC_SUB_CD,
   DESCR,
   DESCRSHORT
FROM  MHRGRP.PS_TGB_CNOCSUB_TBL@CHIPS_LINK;

COMMIT;