TRUNCATE TABLE CHIPS_STG.PS_TGB_CITY_TBL;

INSERT    INTO CHIPS_STG.PS_TGB_CITY_TBL (
  CITY,
  DESCRSHORT,
  PROVINCE,
  COUNTRY,
  TGB_REG_DISTRICT
)
SELECT
  CITY,
  DESCRSHORT,
  PROVINCE,
  COUNTRY,
  TGB_REG_DISTRICT
FROM  MHRGRP.PS_TGB_CITY_TBL@CHIPS_LINK;

COMMIT;