TRUNCATE TABLE CHIPS_STG.PSTREENODE;

INSERT    INTO CHIPS_STG.PSTREENODE (
   SETID,
   SETCNTRLVALUE,
   TREE_NAME,
   EFFDT,
   TREE_NODE_NUM,
   TREE_NODE,
   TREE_BRANCH,
   TREE_NODE_NUM_END,
   TREE_LEVEL_NUM,
   TREE_NODE_TYPE,
   PARENT_NODE_NUM,
   PARENT_NODE_NAME,
   OLD_TREE_NODE_NUM,
   NODECOL_IMAGE,
   NODEEXP_IMAGE
)
SELECT
   SETID,
   SETCNTRLVALUE,
   TREE_NAME,
   EFFDT,
   TREE_NODE_NUM,
   TREE_NODE,
   TREE_BRANCH,
   TREE_NODE_NUM_END,
   TREE_LEVEL_NUM,
   TREE_NODE_TYPE,
   PARENT_NODE_NUM,
   PARENT_NODE_NAME,
   OLD_TREE_NODE_NUM,
   NODECOL_IMAGE,
   NODEEXP_IMAGE
FROM  MHRGRP.PSTREENODE@CHIPS_LINK;

COMMIT;