TRUNCATE TABLE CHIPS_STG.PSXLATITEM;

INSERT    INTO CHIPS_STG.PSXLATITEM (
   FIELDNAME,
   FIELDVALUE,
   EFFDT,
   EFF_STATUS,
   XLATLONGNAME,
   XLATSHORTNAME,
   LASTUPDDTTM,
   LASTUPDOPRID,
   SYNCID
)
SELECT
   FIELDNAME,
   FIELDVALUE,
   EFFDT,
   EFF_STATUS,
   XLATLONGNAME,
   XLATSHORTNAME,
   LASTUPDDTTM,
   LASTUPDOPRID,
   SYNCID
FROM  MHRGRP.PSXLATITEM@CHIPS_LINK;

COMMIT;